set -g prefix C-space
set -g base-index 1
set -g default-shell /bin/zsh
set -g escape-time 0         # zero-out escape time delay
set -g renumber-windows on   # renumber all windows when any window is closed
set -g detach-on-destroy off
set-option -g allow-passthrough on
set-option -sa terminal-features ',xterm-256color:RGB'
set-window-option -g mode-keys vi
setw -g mouse on

set -g status-position top
set -g status-justify absolute-centre
set -g status-style 'bg=default'
set -g status-left ''
set -g status-right ''
setw -g window-status-current-style 'bold'
setw -g window-status-current-format '#[bg=color11]#[fg=black]  #I #W  '
setw -g window-status-format '  #I #W  '

bind -n C-] next-window
bind -n C-[ previous-window
bind t new-window -c "#{pane_current_path}"
bind n new-session
bind c kill-window
bind -n C-( switch-client -p
bind -n C-) switch-client -n
