set-option -sa terminal-features ',xterm-256color:RGB'
set-option -g allow-passthrough on
bind r source-file ~/.config/tmux/tmux.conf
set -g base-index 1

set -g renumber-windows on   # renumber all windows when any window is closed
set -g escape-time 0         # zero-out escape time delay
set-window-option -g mode-keys vi

set -g status-position bottom
set -g status-style 'fg=color1'
set -g status-left ''
set -g status-left-length 10
set -g status-right-style 'fg=black bg=color1'
set -g status-right ''
set -g status-right-length 50
setw -g window-status-current-style 'fg=black bg=color1'
setw -g window-status-current-format ' #I #W #F '
setw -g window-status-style 'fg=green bg=black'
setw -g window-status-format ' #I #[fg=white]#W #[fg=yellow]#F '
setw -g window-status-bell-style 'fg=yellow bg=color1 bold'

bind-key -n M-[ next-window
bind-key -n M-] previous-window
bind-key -n M-t new-window
bind-key -n M-q killp
