set-option -sa terminal-features ',xterm-256color:RGB'
set-option -g allow-passthrough on
bind r source-file ~/.config/tmux/tmux.conf
set -g base-index 1

set -g renumber-windows on   # renumber all windows when any window is closed
set -g escape-time 0         # zero-out escape time delay
set-window-option -g mode-keys vi

set -g status-position bottom
set -g status-justify absolute-centre
set -g status-style 'bg=default'
set -g status-left ''
set -g status-right ''
setw -g window-status-current-style 'bold'
setw -g window-status-current-format '#[fg=color1]#[bg=default]#[fg=black]#[bg=color1] #I #W #[fg=color1]#[bg=default]'
setw -g window-status-format ' #I #W '

bind-key -n C-] next-window
bind-key -n C-[ previous-window
bind-key -n C-t new-window
bind-key -n C-q killp
