hl.config({ autogenerated = false })

require("conf.env")
require("conf.monitors")
require("conf.autostart")
require("conf.appearance")
require("conf.input")
require("conf.keybinds")
require("conf.plugins")
