#################
### AUTOSTART ###
#################

exec-once = hyprpaper
exec-once = hypridle
exec-once = waybar
exec-once = mako
exec-once = mpd
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
