#################
### AUTOSTART ###
#################

exec-once = hyprpaper
exec-once = hypridle
exec-once = waybar
exec-once = mako
exec-once = nm-applet
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = xmodmap -e "clear Lock" -e "keycode 66 = Escape" -e "keycode 9 = Caps_Lock" -e "add Lock = Caps_Lock"
