################
### MONITORS ###
################

# See https://wiki.hyprland.org/Configuring/Monitors/
monitor=DP-1,1920x1080@165,auto,auto
monitor=HDMI-A-1,preferred,auto,1.5
monitor=eDP-1,preferred,auto,auto
