vim.pack.add({
	"https://github.com/L3MON4D3/LuaSnip",
	"https://github.com/WhoIsSethDaniel/mason-tool-installer.nvim",
	"https://github.com/folke/todo-comments.nvim",
	"https://github.com/geg2102/nvim-jupyter-client",
	"https://github.com/geg2102/nvim-python-repl",
	"https://github.com/hrsh7th/cmp-nvim-lsp",
	"https://github.com/hrsh7th/cmp-path",
	"https://github.com/hrsh7th/nvim-cmp",
	"https://github.com/kevinhwang91/nvim-ufo",
	"https://github.com/kevinhwang91/promise-async",
	"https://github.com/lambdalisue/vim-suda",
	"https://github.com/lewis6991/gitsigns.nvim",
	"https://github.com/neovim/nvim-lspconfig",
	"https://github.com/norcalli/nvim-colorizer.lua",
	"https://github.com/nvim-lua/plenary.nvim",
	"https://github.com/nvim-lualine/lualine.nvim",
	"https://github.com/nvim-mini/mini.nvim",
	"https://github.com/nvim-tree/nvim-web-devicons",
	"https://github.com/nvim-treesitter/nvim-treesitter",
	"https://github.com/onsails/lspkind.nvim",
	"https://github.com/saadparwaiz1/cmp_luasnip",
	"https://github.com/stevearc/conform.nvim",
	"https://github.com/stevearc/oil.nvim",
	"https://github.com/williamboman/mason-lspconfig.nvim",
	"https://github.com/williamboman/mason.nvim",
	"https://github.com/windwp/nvim-ts-autotag",

	"https://github.com/kaarmu/typst.vim",
	"https://github.com/mrcjkb/rustaceanvim",
	-- "~/Projects/cheesepizza.nvim",

	"https://github.com/rebelot/kanagawa.nvim",
})
