vim.pack.add({
	"https://github.com/L3MON4D3/LuaSnip",
	"https://github.com/MunifTanjim/nui.nvim",
	"https://github.com/WhoIsSethDaniel/mason-tool-installer.nvim",
	"https://github.com/akinsho/toggleterm.nvim",
	"https://github.com/andrew-george/telescope-themes",
	"https://github.com/brenoprata10/nvim-highlight-colors",
	"https://github.com/folke/lazydev.nvim",
	"https://github.com/folke/noice.nvim",
	"https://github.com/folke/todo-comments.nvim",
	"https://github.com/geg2102/nvim-jupyter-client",
	"https://github.com/geg2102/nvim-python-repl",
	"https://github.com/hrsh7th/cmp-buffer",
	"https://github.com/hrsh7th/cmp-nvim-lsp",
	"https://github.com/hrsh7th/cmp-path",
	{
		src = "https://github.com/hrsh7th/nvim-cmp",
		data = {
			opts = function(_, opts)
				opts.sources = opts.sources or {}
				table.insert(opts.sources, {
					name = "lazydev",
					group_index = 0,
				})
			end,
		},
	},
	"https://github.com/kevinhwang91/nvim-ufo",
	"https://github.com/kevinhwang91/promise-async",
	"https://github.com/lambdalisue/vim-suda",
	"https://github.com/lewis6991/gitsigns.nvim",
	"https://github.com/neovim/nvim-lspconfig",
	"https://github.com/numToStr/Comment.nvim",
	"https://github.com/nvim-lua/plenary.nvim",
	"https://github.com/nvim-lualine/lualine.nvim",
	"https://github.com/nvim-mini/mini.nvim",
	"https://github.com/nvim-telescope/telescope-fzf-native.nvim",
	"https://github.com/nvim-telescope/telescope.nvim",
	"https://github.com/nvim-tree/nvim-web-devicons",
	"https://github.com/nvim-treesitter/nvim-treesitter",
	"https://github.com/onsails/lspkind.nvim",
	"https://github.com/rafamadriz/friendly-snippets",
	"https://github.com/rcarriga/nvim-notify",
	"https://github.com/saadparwaiz1/cmp_luasnip",
	"https://github.com/stevearc/conform.nvim",
	"https://github.com/stevearc/oil.nvim",
	"https://github.com/williamboman/mason-lspconfig.nvim",
	"https://github.com/williamboman/mason.nvim",
	"https://github.com/windwp/nvim-autopairs",
	"https://github.com/windwp/nvim-ts-autotag",

	"https://github.com/fatih/vim-go",
	"https://github.com/kaarmu/typst.vim",
	"https://github.com/regarager/cheesepizza.nvim",
	"https://github.com/mrcjkb/rustaceanvim",

	"https://github.com/EdenEast/nightfox.nvim",
	"https://github.com/rebelot/kanagawa.nvim",

	"https://github.com/IogaMaster/neocord",
})
