#!/usr/bin/env bash

echo -n "Enter query: "; yt-dlp --embed-metadata --embed-thumbnail --merge-output-format mkv \
  -f bestaudio -x --audio-format mp3 --audio-quality 320k \
  "https://youtube.com/watch?v=$(read query; yt-dlp ytsearch20:"$query" --print "%(title)s [%(id)s]" --flat-playlist | /bin/cat -n | fzf --no-sort --reverse | awk '{print $NF}' | tr -d "[]")" -o "%(title)s"
