# This is the configuration file for catnap.
# Here you can configure the stat colors,
# stat names, stat icons and more!
#
# https://github.com/iinsertNameHere/catnap

##############################################
##          FetchInfo stats Config          ##
##############################################
[stats]
# username  = {icon = " ", name = "user", color = "(RD)"}
hostname  = {icon = " ", name = "hostname", color = "(RD)"}
# uptime    = {icon = " ", name = "uptime", color = "(YW)"}
distro    = {icon = " ", name = "distro", color = "(YW)"}
kernel    = {icon = " ", name = "kernel", color = "(GN)"}
desktop   = {icon = " ", name = "desktp", color = "(CN)"}
terminal  = {icon = " ", name = "term", color = "(BE)"}
shell     = {icon = " ", name = "shell", color = "(BE)"}
# packages  = {icon = " ", name = "packages", color = "(GN)"}  # WARNING: Resource Intensive
# gpu       = {icon = "󱔐 ", name = "gpu", color = "(MA)"}      # WARNING: Resource Intensive
# cpu       = {icon = " ", name = "cpu", color = "(RD)"}
# disk_0    = {icon = " ", name = "disk", color = "(GN)"}
memory    = {icon = " ", name = "memory", color = "(MA)"}
uptime    = {icon = " ", name = "uptime", color = "(GN)"}
# weather   = {icon = " ", name = "weather", color = "(BE)"} # Requires curl and an emoji font. | WARNING: Resource Intensive
sep_color = "SEPARATOR"
colors    = {icon = " ", name = "colors", color = "!DT!", symbol = ""}

##############################################
##               Misc Config                ##
##############################################
[misc]
borderstyle = "line"
layout = "Inline" # [Inline, ArtOnTop, StatsOnTop]
stats_margin_top = 0

[misc.figletLogos] # Requires Figlet.
enable = false
color  = "(YW)"
font   = "slant"
margin = [0, 0, 0,]

[misc.imageMode] # Requires Viu.
enable = false
path   = "/path/to/some/image.png" # Please only use absolute paths.
scale  = 18
margin = [2, 2, 3,]
