import = [
	"~/.config/alacritty/themes/themes/dracula.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 0
padding.y = 0
opacity = 0.9

[font]
normal.family = "JetBrains Mono"
size = 10

[shell]
program = "/usr/bin/zsh"
