[general]
import = [
	"~/.config/alacritty/themes/themes/tokyo-night-storm.toml"
]

[window]
padding.x = 0
padding.y = 0
opacity = 1.0

[font]
normal.family = "ComicShanns Nerd Font"
size = 11

[keyboard]
bindings = [
   { key = "Enter", mods = "Control", action = "SpawnNewInstance" }
]

[terminal.shell]
program = "/usr/bin/zsh"

[env]
TERM = "xterm-256color"
EDITOR = "/usr/bin/nvim"
