import = [
	"~/.config/alacritty/themes/themes/kanagawa-wave.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 0
padding.y = 0
opacity = 0.75

[font]
normal.family = "JetBrains Mono"
size = 10

[shell]
program = "/usr/bin/zsh"

[keyboard]
bindings = [
   { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" }
]
