import = [
	"~/.config/alacritty/themes/themes/tokyonight.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 0
padding.y = 0
opacity = 0.75

[font]
normal.family = "ComicShanns Nerd Font"
size = 11

[shell]
program = "/usr/bin/zsh"

[keyboard]
bindings = [
   { key = "Enter", mods = "Control", action = "SpawnNewInstance" }
]
