import = [
	"~/.config/alacritty/themes/themes/nordic.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 0
padding.y = 0
opacity = 0.75

[font]
normal.family = "0xProto"
size = 10

[shell]
program = "/usr/bin/zsh"
