[env]
TERM = "xterm-256color"

[window]
padding.x = 0
padding.y = 0
opacity = 0.70

[font]
normal.family = "ComicShanns Nerd Font"
size = 11

[terminal.shell]
program = "/usr/bin/zsh"

[keyboard]
bindings = [
   { key = "Enter", mods = "Control", action = "SpawnNewInstance" }
]

[general]
import = [
	"~/.config/alacritty/themes/themes/tokyo-night-storm.toml"
]

[terminal]
